name: appwrite_sdk_issue_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  dart_appwrite: ^19.2.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
